export const GET_LIST_CHARACTERS = 'GET_LIST_CHARACTERS'
export const GET_LIST_CHARACTERS_SUCCESS = 'GET_LIST_CHARACTERS_SUCCESS'
export const GET_LIST_CHARACTERS_FAILURE = 'GET_LIST_CHARACTERS_FAILURE'
