import errorCodes from './errors';
import validations from './validations';

export default string = {
  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    continue: 'Continue',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    delete: 'Delete',
    search: 'Search',
  },
  login: {
    title: 'Login',
    signupButton: 'Register an account?',
    loginButton: 'Login',
  },
  signup: {
    title: 'Sign Up',
    policyAgreement: "By tapping Register, I agree to DOM's ",
    terms: 'Term of Service',
    and: ' and ',
    privacy: 'Privacy Statement',
    registerButton: 'Register',
    nextButton: 'Next',
  },
  work: {
    title: 'Work',
    welcome: 'Welcome, {{0}}',
  },
  calendar: {
    title: 'Calendar',
  },
  manage: {
    title: 'Manage',
  },
  message: {
    title: 'Messages',
    deleteMessage: 'Delete message?',
    confirmDeleteMessage: 'Do you really want to delete this message?',
    suggest: 'Suggest',
    newMessage: 'New message',
    friends: 'Friends',
  },
  controls: {
    email: 'Email',
    phone: 'Phone',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm password',
  },
  verifyCode: {
    title: 'Confirm Phone Number',
    fieldInput: 'Verification code',
  },
  tripsList: {
    provider: 'Provider',
    start: 'Start',
    done: 'Done',
    route_task: 'Route/Task',
    neighborhood: 'Neighborhood',
    job: 'Job',
    required_work: 'Required work',
    trips: 'Trips',
  },
  tripDetail: {
    complete: 'Complete',
    resume: 'Resume',
    pause: 'Pause/Problem',
    trip_completed: 'Trip Completed',
    cancelled: 'Cancelled',
  },
  addNewTrip: {
    eventLabel: 'Select Event :',
    selectEvent: 'Select Event',
    routeLabel: 'Select Route :',
    selectRoute: 'Select Route',
    conditionLabel: 'Road Condition :',
    selectCondition: 'Select Road Condition',
  },
  activeGeofences: {
    title: 'Active geofences',
  },
  contactsList: {
    title: 'Contacts List',
  },
  more: {
    profile: 'Profile',
    tripSettings: 'Trip Settings',
    geofences: 'Geofences',
    signout: 'Sign Out',
    developer: 'Developer',
    settings: 'Settings',
  },
  profile: {
    title: 'Update Profile',
    save: 'Save',
    address: 'Address',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    updateSuccessfully: 'Updated successfully!',
  },
  settings: {
    geoModal: 'Geofence Notification',
    geoVoice: 'Geofence Voice Confirmation',
    geoRadius: 'Geofence Detectable Radius',
    currentRadius: 'Current radius is: {{value}} meters',
    // trackingStrategy: 'Tracking Strategy',
    trackingStrategy: 'Geofence Notification Override',
    never: 'Never',
    checkinRequired: 'Only if checkin/checkout is required',
    always: 'Always',
    geoModalDescription: 'Prompt when a geofence is triggered?',
  },
  contractDetail: {
    comments: 'Private Comments',
    photos: 'Photos',
    eta: 'ETA',
    workEST: 'Work est: {{value}}',
    info: 'Info',
    instruction: 'Instruction:',
    dumpZone: 'Dump Zone:',
    notes: 'Notes',
  },
  jobDetail: {
    comments: 'Private Comments',
    photos: 'Photos',
    notes: 'Notes',
    info: 'Info',
    savedInfoSuccessfully: 'Saved successfully!',
    services: 'Services',
    name: 'Name: ',
    instructions: 'Instructions: ',
  },
  routes: {
    properties: 'Total: {{value}} properties',
  },
  time: {
    min: 'mins',
  },
  errorCodes,
  validations,
};
