export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE'

export const SEND_COMMENT = 'SEND_COMMENT'
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_FAILURE = 'SEND_COMMENT_FAILURE'
