export const GET_CHARACTER_DETAIL = 'GET_CHARACTER_DETAIL'
export const GET_CHARACTER_DETAIL_SUCCESS = 'GET_CHARACTER_DETAIL_SUCCESS'
export const GET_CHARACTER_DETAIL_FAILURE = 'GET_CHARACTER_DETAIL_FAILURE'

export const GET_QUOTE = 'GET_QUOTE'
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS'
export const GET_QUOTE_FAILURE = 'GET_QUOTE_FAILURE'
